name: Daily Schedule Trigger

on:
  schedule:
    # Berjalan setiap hari pada jam 18:15 UTC (Sama dengan jam 01:15 WIB)
    - cron: '15 18 * * *'
  workflow_dispatch: # Mengizinkan trigger manual dari tombol di GitHub

jobs:
  trigger-api:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Call NestJS Endpoint (Eksekusi Pertama)
        run: |
          curl -X POST ${{ secrets.API_URL }} \
          -H "x-api-key: ${{ secrets.CRON_SECRET_KEY }}" \
          -H "Content-Type: application/json"
      - name: Tunggu 90 detik sebelum pemanggilan berikutnya
        run: sleep 90
      - name: Call NestJS Endpoint (Eksekusi Kedua)
        run: |
          curl -X POST ${{ secrets.API_URL }} \
          -H "x-api-key: ${{ secrets.CRON_SECRET_KEY }}" \
          -H "Content-Type: application/json"
      - name: Tunggu 90 detik sebelum pemanggilan berikutnya
        run: sleep 90
      - name: Call NestJS Endpoint (Eksekusi Ketiga)
        run: |
          curl -X POST ${{ secrets.API_URL }} \
          -H "x-api-key: ${{ secrets.CRON_SECRET_KEY }}" \
          -H "Content-Type: application/json"
      - name: Tunggu 90 detik sebelum pemanggilan berikutnya
        run: sleep 90
      - name: Call NestJS Endpoint (Eksekusi Keempat)
        run: |
          curl -X POST ${{ secrets.API_URL }} \
          -H "x-api-key: ${{ secrets.CRON_SECRET_KEY }}" \
          -H "Content-Type: application/json"