name: Daily Schedule Trigger

on:
  schedule:
    # Berjalan setiap hari pada jam 17:00 UTC (Sama dengan jam 00:00 WIB tengah malam)
    - cron: '0 17 * * *'
  workflow_dispatch: # Mengizinkan trigger manual dari tombol di GitHub

jobs:
  trigger-api:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Call NestJS Endpoint (Eksekusi Pertama)
        run: |
          curl -X POST ${{ secrets.API_URL }} \
          -H "x-api-key: ${{ secrets.CRON_SECRET_KEY }}" \
          -H "Content-Type: application/json"
      - name: Tunggu 60 detik sebelum pemanggilan berikutnya
        run: sleep 60
      - name: Call NestJS Endpoint (Eksekusi Kedua)
        run: |
          curl -X POST ${{ secrets.API_URL }} \
          -H "x-api-key: ${{ secrets.CRON_SECRET_KEY }}" \
          -H "Content-Type: application/json"
      - name: Tunggu 60 detik sebelum pemanggilan berikutnya
        run: sleep 60
      - name: Call NestJS Endpoint (Eksekusi Ketiga)
        run: |
          curl -X POST ${{ secrets.API_URL }} \
          -H "x-api-key: ${{ secrets.CRON_SECRET_KEY }}" \
          -H "Content-Type: application/json"